#ifndef OMPPARSER_OMPPARSER_CONFIG_H
#define OMPPARSER_OMPPARSER_CONFIG_H

#define OMPPARSER_VERSION_MAJOR    @OMPPARSER_VERSION_MAJOR@
#define OMPPARSER_VERSION_MINOR    @OMPPARSER_VERSION_MINOR@
#define OMPPARSER_VERSION          @OMPPARSER_VERSION@

#endif /* OMPPARSER_OMPPARSER_CONFIG_H */
